live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 25
y = 20

[font]
#normal.family = "ZedMono Nerd Font"
normal.family = "MesloLGS Nerd Font Mono"

size = 16.0

import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]
