live_config_reload = true
working_directory = "/Users/fakrul/Downloads/"

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 25
y = 20

[font]
#normal.family = "ZedMono Nerd Font"
normal.family = "MesloLGS Nerd Font Mono"
size = 15.0

[bell]
animation = "Ease"

[selection]
save_to_clipboard = true

import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]
